TopSpeed.Web/Models/Brand.cs
using System.ComponentModel.DataAnnotations;

namespace TopSpeed.Web.Models
{
    public class Brand
    {
        [Key]
        public Guid Id { get; set; }
        [Required]
        public string Name { get; set; }=string.Empty;
       [Display(Name="Established Year")]
        public int EstablishedYear { get; set; }
        [Display(Name = "Brand Logo")]
        public string BrandLogo { get; set; } = string.Empty;
    }
}

TopSpeed.Web/Models/ErrorViewModel.cs
namespace TopSpeed.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TopSpeed.Web/Controllers/BrandController.cs
using Microsoft.AspNetCore.Mvc;
using TopSpeed.Web.Data;
using TopSpeed.Web.Models;

namespace TopSpeed.Web.Controllers
{
    public class BrandController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public BrandController(ApplicationDbContext dbContext, IWebHostEnvironment webHostEnvironment)
        {
            _dbContext = dbContext;
            _webHostEnvironment = webHostEnvironment;
        }

        [HttpGet]
        public IActionResult Index()
        {
            List<Brand> brands = _dbContext.Brands.ToList();
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Brand brand)
        {
            string webRootPath=_webHostEnvironment.WebRootPath;

            var file = HttpContext.Request.Form.Files;

            if (file.Count > 0)
            {
                string newFileName= Guid.NewGuid().ToString();

                var upload = Path.Combine(webRootPath, @"images\brand");
         
                var extension = Path.GetExtension(file[0].FileName);

                using (var fileStream = new FileStream(Path.Combine(upload, newFileName + extension), FileMode.Create))
                {
                    file[0].CopyTo(fileStream);
                }

                brand.BrandLogo=@"\images\brand\"+newFileName+extension;
            }

            //validation
            if (ModelState.IsValid)
            {
                _dbContext.Brands.Add(brand);
                _dbContext.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            return View();
        }
    }
}

TopSpeed.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TopSpeed.Web.Models;

namespace TopSpeed.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TopSpeed.Web/Views/Brand/Create.cshtml
@model Brand

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2 class="text-uppercase text-center">Create Brand</h2>

        </div>

    </div>
    <div class="row">
        <div col-md-12 border-1 border>
            <form method="post" enctype="multipart/form-data">
                <div class="md-3">
                    <label asp-for="@Model.Name" class="form-label"></label>
                    <input asp-for="@Model.Name" class="form-control">
                    <span asp-validation-for="@Model.Name" class="text-danger"></span>
                </div>
                <div class="md-3">
                    <label asp-for="@Model.EstablishedYear" class="form-label"></label>
                    <input asp-for="@Model.EstablishedYear" class="form-control">
                    <span asp-validation-for="@Model.EstablishedYear" class="text-danger"></span>
                </div>
                <div class="md-3">
                    <label asp-for="@Model.BrandLogo" class="form-label"></label>
                    <input type="file" name="files" id="uploadBox" class="form-control">
                </div>
                <div class="md-3">
                    <a asp-controller="Brand" asp-action="Index" class="btn btn-danger">Back</a>
                   <button type="submit" class="btn btn-success">Create</button>
                </div>
            </form>

        </div>

    </div>
</div>


@section Scripts{
    <partial name="_validationScriptsPartial"/>
}

TopSpeed.Web/Views/Brand/Index.cshtml
@model List<Brand>

<div class="container">
    <div class="row mb-4">
        <div class="col-md-6 text-uppercase">
            <h2>Brand List</h2>
        </div>
        <div class="col-md-6 text-end">
            <a asp-controller="Brand" asp-action="Create" class="btn btn-primary"><i class="bi bi-plus-circle"></i>Create</a>
        </div>

    </div>
    <hr />

        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Established Year</th>
                </tr>
            </thead>
            <tbody>
             

            @if (Model != null && Model.Any())
            {
                foreach (var item in Model)
                {
                    <!-- Display item properties here -->
                    <tr>
                        <td>@item.Name</td>
                        <td>@item.EstablishedYear</td>
                    </tr>
                }
            }
            else
            {
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h2 class="text-center-uppercase text-warning pt-4">No Records</h2>

                        </div>

                    </div>

                </div>
            }


            </tbody>
        </table>
  
</div>

TopSpeed.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TopSpeed.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TopSpeed.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TopSpeed.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TopSpeed.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Brand" asp-action="Index">Brand</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - TopSpeed.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>